### ISSUE TITLE
New release with updated deps

### ISSUE THREAD

**Issue by roflmaostc** [mkitti/Napari.jl#16]
Hey,

could you maybe release a new version with the updated deps?

Thanks a lot and I'm glad this packages exists (using it daily ;)),

Felix

**Comment by mkitti** [comment]
You might be using it more than myself. Do you need any other changes or just release it as it is on the main branch?

One change I'm considering is incorporating [NumPyArrays.jl](https://github.com/mkitti/NumPyArrays.jl) to make [image handling](https://github.com/mkitti/Napari.jl/blob/main/src/image.jl) more efficient. Maybe I'll just issue a point release (0.1.1) for you and then make those changes in 0.2.0.

**Comment by roflmaostc** [comment]
What are you using for 3D data btw?

Thanks a lot!

**Comment by mkitti** [comment]
This is definitely a topic of many discussions we have had at Janelia since the Napari API seems plane focused while our 3D data formats are increasingly chunk based. Most of the 3D data we have been working with ends up in either BigDataViewer, Neuroglancer, or VVD_Viewer. I want to take a closer look at how Napari is digesting Zarr data.

**Comment by mkitti** [comment]
v0.1.1 released:
https://github.com/mkitti/Napari.jl/releases/tag/v0.1.1
